#!/usr/bin/env bash
## tranfer using scp given 4 args to the script

if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
fi
scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
