#!/usr/bin/env bash
# unblock nginx port 80
sudo apt install -y update
sudo apt remove -y nginx nginx-common
sudo apt purge -y nginx nginx-common
sudo apt install -y nginx
sudo ufw allow "Nginx HTTP"
sudo service nginx restart
