#!/usr/bin/env bash
# Configures an Ubuntu server with localhost 127.0.0.2
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1 localhost/127.0.0.2 localhost/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
